name: "erp_api"

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - '${POSTGRES_PORT}:5432'
    # restart: unless-stopped
    networks:
      - internal
  
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:3306'
    networks:
      - internal

networks:
  internal:
    driver: bridge
