# Generated by Django 4.2.4 on 2024-11-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_taskstatus_tasks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tasks",
            new_name="Task",
        ),
    ]
