# Generated by Django 4.2.4 on 2024-11-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_alter_employee_id_alter_taskstatus_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(null=True),
        ),
    ]
